name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          readarray -t added_modified_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for((i=0;i<${#added_modified_files[@]};i++)){
              echo "Do something with this ${added_modified_files[$i]}."
          }

      - name: Install ssh key
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

    #   - name: ENV
    #     env:
    #       BASH_SECRET: ${{ secrets.BASH_SHELL }}
    #     run: ssh alarm@96.9.77.65 'touch /home/alarm/file_by_brilliant_from_github.text'

    #   - name: Add permission
    #     run: chmod +x run-bash-secret

    #   - name: Deploy...
    #     run: ./run-bash-secret
