name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          readarray -t added_modified_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for added_modified_file in ${added_modified_files[@]}; do
              echo "Do something with this ${added_modified_file%/*}."
          done
        #   echo "Added:"
        #   echo "${{ steps.abc.outputs.added }}"
        #   echo "${{ steps.abc.outputs.modified }}"
        #   echo "Added+Modified:"
        #   echo "All:"
        #   echo "${{ steps.abc.outputs.all }}"
        #   echo "Removed:"
        #   echo "${{ steps.abc.outputs.removed }}"
        #   echo "Renamed:"
        #   echo "${{ steps.abc.outputs.renamed }}"
        #   echo "Modified:"
        #   echo "${{ steps.abc.outputs.added_modified }}"
